USE roaming_audit;

ALTER TABLE partners
ADD COLUMN tadig_code VARCHAR(10) NOT NULL AFTER country,
ADD COLUMN last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at; 